CREATE TABLE CLIENTE (
  ID INTEGER NOT NULL,
  NOME VARCHAR(60) NOT NULL,
  CNPJ VARCHAR(18),
  SERIAL VARCHAR(20) NOT NULL,
  TIPO SMALLINT,
  TELEFONE VARCHAR(18),
  CONTADOR INTEGER NOT NULL);


ALTER TABLE CLIENTE ADD PRIMARY KEY (ID);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE 
FOREIGN KEY (CONTADOR) REFERENCES CONTADOR(ID);
