CREATE TABLE CONTADOR (
  ID INTEGER NOT NULL,
  NOME VARCHAR(60) NOT NULL,
  CNPJ VARCHAR(18),
  TELEFONE VARCHAR(18) COLLATE NONE,
  EMAIL VARCHAR(60) NOT NULL);


ALTER TABLE CONTADOR ADD PRIMARY KEY (ID);
