DROP TABLE STATUS;

CREATE TABLE STATUS (
  ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(40) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252,
  MODIFICADO DATE,
  USERNAME INTEGER NOT NULL);


ALTER TABLE STATUS ADD PRIMARY KEY (ID);

ALTER TABLE STATUS ADD CONSTRAINT FK_STATUS_USERNAME FOREIGN KEY (USERNAME) REFERENCES STATUS(ID);


CREATE TRIGGER BI_STATUS_ID FOR STATUS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(STATUS_ID_GEN, 1);
END;
